// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fileinfo

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GoFileInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsGoFileInfo(buf []byte, offset flatbuffers.UOffsetT) *GoFileInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GoFileInfo{}
	x.Init(buf, n+offset)
	return x
}

func FinishGoFileInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsGoFileInfo(buf []byte, offset flatbuffers.UOffsetT) *GoFileInfo {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &GoFileInfo{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedGoFileInfoBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *GoFileInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GoFileInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GoFileInfo) Filename() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GoFileInfo) NumImports() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *GoFileInfo) MutateNumImports(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func GoFileInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GoFileInfoAddFilename(builder *flatbuffers.Builder, filename flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(filename), 0)
}
func GoFileInfoAddNumImports(builder *flatbuffers.Builder, numImports int32) {
	builder.PrependInt32Slot(1, numImports, 0)
}
func GoFileInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
